# Generated by Django 4.2.11 on 2024-04-29 16:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uusername', models.CharField(db_column='uUsername', max_length=50, unique=True)),
                ('upassword', models.CharField(db_column='uPassword', max_length=128)),
                ('uemail', models.CharField(db_column='uEmail', max_length=64)),
                ('ufname', models.CharField(db_column='uFName', max_length=64)),
                ('ulname', models.CharField(db_column='uLName', max_length=64)),
                ('uregdate', models.DateTimeField(db_column='uRegDate')),
                ('uprofilepic', models.CharField(db_column='uProfilePic', max_length=100)),
                ('uprofilebgpic', models.CharField(db_column='uProfileBgPic', max_length=100)),
                ('udesc', models.CharField(db_column='uDesc', max_length=100)),
                ('uip', models.CharField(db_column='uIp', max_length=100)),
                ('ucids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='ucIDs', size=None)),
            ],
        ),
    ]
