# Generated by Django 4.2.11 on 2024-05-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagement', '0002_user_uis42_alter_user_id_alter_user_udesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uemail',
            field=models.CharField(db_column='uEmail', default='', max_length=64, unique=True),
        ),
    ]
