# Generated by Django 4.2.13 on 2024-05-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagement', '0003_alter_user_uemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pmatchesplayed', models.IntegerField(db_column='pMatchesPlayed')),
                ('pmatcheswon', models.IntegerField(db_column='pMatchesWon')),
                ('pmatcheslost', models.IntegerField(db_column='pMatchesLost')),
                ('pxp', models.IntegerField(db_column='pXP')),
                ('prank', models.IntegerField(db_column='pLevel')),
            ],
        ),
    ]
