# Generated by Django 4.2.13 on 2024-05-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagement', '0004_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='pmatcheslost',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pmatchesplayed',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pmatcheswon',
        ),
        migrations.RemoveField(
            model_name='player',
            name='prank',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pxp',
        ),
        migrations.AddField(
            model_name='player',
            name='matcheslost',
            field=models.IntegerField(db_column='MatchesLost', default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='matchesplayed',
            field=models.IntegerField(db_column='MatchesPlayed', default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='matcheswon',
            field=models.IntegerField(db_column='MatchesWon', default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.IntegerField(db_column='Level', default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='xp',
            field=models.IntegerField(db_column='XP', default=0),
        ),
    ]
