# Generated by Django 4.2.13 on 2024-05-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagement', '0006_delete_player_user_matcheslost_user_matchesplayed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(db_column='Level', default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='udiscordid',
            field=models.CharField(db_column='uDiscordID', default='', max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='utitle',
            field=models.CharField(db_column='uTitle', default='', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='utournamentslost',
            field=models.IntegerField(db_column='uTournamentsLost', default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='utournamentsplayed',
            field=models.IntegerField(db_column='uTournamentsPlayed', default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='utournamentswon',
            field=models.IntegerField(db_column='uTournamentsWon', default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(db_column='Rank', default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='uemail',
            field=models.CharField(db_column='uEmail', max_length=64, unique=True),
        ),
    ]
