# Generated by Django 4.2.13 on 2024-05-20 09:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagement', '0011_matchhistory_matchtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ucids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='ucIDs', default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='udiscordid',
            field=models.CharField(db_column='uDiscordID', default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='uemail',
            field=models.CharField(db_column='uEmail', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ufname',
            field=models.CharField(db_column='uFName', default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='uip',
            field=models.CharField(db_column='uIp', default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='ulname',
            field=models.CharField(db_column='uLName', default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='utitle',
            field=models.CharField(db_column='uTitle', default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='uusername',
            field=models.CharField(db_column='uUsername', max_length=24, unique=True),
        ),
    ]
