# Generated by Django 4.2.13 on 2024-05-25 13:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagement', '0012_alter_user_ucids_alter_user_udiscordid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ABlocked',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='ABlocked', default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='ABlockedBy',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='ABlockedBy', default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='AFriends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='AFriends', default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='ARequests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='ARequests', default=list, size=None),
        ),
    ]
