# Generated by Django 4.2.13 on 2024-05-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagement', '0012_alter_user_ucids_alter_user_udiscordid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nType', models.CharField(db_column='nType', default='', max_length=16)),
                ('nContent', models.CharField(db_column='nContent', default='', max_length=100)),
                ('nDate', models.DateTimeField(db_column='nDate', default='')),
                ('nRead', models.BooleanField(db_column='nRead', default=False)),
                ('nReciever', models.IntegerField(db_column='nUser', default=-1)),
                ('nSender', models.IntegerField(db_column='nSender', default=-1)),
            ],
        ),
    ]
