# Generated by Django 4.2.13 on 2024-05-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagement', '0013_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='nRead',
        ),
    ]
