# Generated by Django 4.2.13 on 2024-06-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagement', '0015_user_ablocked_user_ablockedby_user_arequests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uprofilebgpic',
            field=models.ImageField(db_column='uProfileBgPic', default='', upload_to='profile_bg_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uprofilepic',
            field=models.ImageField(db_column='uProfilePic', default='/static/img/pfp/Default.png', upload_to='profile_pics/'),
        ),
    ]
