# Generated by Django 4.2.13 on 2024-06-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagement', '0017_user_twofactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uprofilebgpic',
            field=models.ImageField(default='', upload_to='profile_bg_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uprofilepic',
            field=models.ImageField(default='/static/img/pfp/Default.png', upload_to='profile_pics/'),
        ),
    ]
