# Generated by Django 4.2.13 on 2024-06-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagement', '0019_alter_user_uprofilebgpic_alter_user_uprofilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isOnline',
            field=models.BooleanField(db_column='online', default=False),
        ),
    ]
