# Generated by Django 4.2.13 on 2024-08-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagement', '0014_user_twofactor'),
        ('UserDataManagement', '0020_user_isonline'),
    ]

    operations = [
    ]
