# Generated by Django 4.2.13 on 2024-08-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagement', '0021_merge_0014_user_twofactor_0020_user_isonline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.FloatField(db_column='level', default=0),
        ),
    ]
