# Generated by Django 4.2.13 on 2024-06-07 11:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_user_isonline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('chID', models.AutoField(primary_key=True, serialize=False)),
                ('chName', models.CharField(db_column='chName', default='', max_length=50)),
                ('chMembers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='chMembers', default=list, size=None)),
                ('chDesc', models.CharField(db_column='chDesc', default='', max_length=100)),
                ('chAdmin', models.IntegerField(db_column='chAdmin', default=0)),
                ('chCreated', models.DateTimeField(auto_now_add=True, db_column='chCreated')),
                ('chUpdated', models.DateTimeField(auto_now=True, db_column='chUpdated')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chID', models.IntegerField(db_column='chID', default=0)),
                ('cmContent', models.TextField(db_column='cmContent', default='')),
                ('cmSender', models.IntegerField(db_column='cmSender', default=0)),
                ('cmCreated', models.DateTimeField(auto_now_add=True, db_column='cmCreated')),
                ('cmUpdated', models.DateTimeField(auto_now=True, db_column='cmUpdated')),
                ('cmRead', models.BooleanField(db_column='cmRead', default=False)),
            ],
        ),
    ]
