# Generated by Django 4.2.13 on 2024-06-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isOnline',
            field=models.BooleanField(db_column='online', default=False),
        ),
    ]
