# Generated by Django 4.2.11 on 2024-05-01 09:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uusername', models.CharField(db_column='uUsername', default='', max_length=50, unique=True)),
                ('upassword', models.CharField(db_column='uPassword', default='', max_length=128)),
                ('uemail', models.CharField(db_column='uEmail', default='', max_length=64)),
                ('ufname', models.CharField(db_column='uFName', default='', max_length=64)),
                ('ulname', models.CharField(db_column='uLName', default='', max_length=64)),
                ('uregdate', models.DateTimeField(db_column='uRegDate', default='')),
                ('uprofilepic', models.CharField(db_column='uProfilePic', default='', max_length=100)),
                ('uprofilebgpic', models.CharField(db_column='uProfileBgPic', default='', max_length=100)),
                ('udesc', models.CharField(db_column='uDesc', default='', max_length=100)),
                ('uip', models.CharField(db_column='uIp', default='', max_length=100)),
                ('ucids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='ucIDs', size=None)),
            ],
            options={
                'db_table': 'UserDataManagement_user',
            },
        ),
    ]
