# Generated by Django 4.2.11 on 2024-05-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='udesc',
            new_name='uDesc',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='uemail',
            new_name='uEmail',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='ufname',
            new_name='uFname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='uip',
            new_name='uIp',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='ulname',
            new_name='uLname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='upassword',
            new_name='uPassword',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='uprofilebgpic',
            new_name='uProfilebgpic',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='uprofilepic',
            new_name='uProfilepic',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='uregdate',
            new_name='uRegdate',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='uusername',
            new_name='uUsername',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='ucids',
            new_name='ucIDs',
        ),
    ]
