# Generated by Django 4.2.13 on 2024-06-09 09:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_remove_users_uprofilebgpic_remove_users_uprofilepic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secret', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 9, 9, 43, 35, 121673))),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2024, 6, 9, 9, 48, 35, 121691))),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.users')),
            ],
            options={
                'db_table': 'UserDataManagement_twofactor',
            },
        ),
    ]
