# Generated by Django 4.2.13 on 2024-06-09 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_twofactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 9, 44, 54, 891968, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='twofactor',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 9, 49, 54, 892115, tzinfo=datetime.timezone.utc)),
        ),
    ]
