# Generated by Django 4.2.13 on 2024-06-09 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_alter_twofactor_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 10, 5, 40, 167786, tzinfo=datetime.timezone.utc)),
        ),
    ]
