# Generated by Django 4.2.13 on 2024-06-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_alter_twofactor_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactor',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
