# Generated by Django 4.2.13 on 2024-06-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_alter_twofactor_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactor',
            name='expires_at',
        ),
    ]
