# Generated by Django 4.2.14 on 2024-08-06 12:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('chID', models.AutoField(primary_key=True, serialize=False)),
                ('chName', models.CharField(db_column='chName', default='', max_length=50)),
                ('chMembers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='chMembers', default=list, size=None)),
                ('chDesc', models.CharField(db_column='chDesc', default='', max_length=100)),
                ('chAdmin', models.IntegerField(db_column='chAdmin', default=0)),
                ('chCreated', models.DateTimeField(auto_now_add=True, db_column='chCreated')),
                ('chUpdated', models.DateTimeField(auto_now=True, db_column='chUpdated')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chID', models.IntegerField(db_column='chID', default=0)),
                ('cmContent', models.TextField(db_column='cmContent', default='')),
                ('cmSender', models.IntegerField(db_column='cmSender', default=0)),
                ('cmCreated', models.DateTimeField(auto_now_add=True, db_column='cmCreated')),
                ('cmUpdated', models.DateTimeField(auto_now=True, db_column='cmUpdated')),
                ('cmRead', models.BooleanField(db_column='cmRead', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cName', models.CharField(db_column='cName', default='', max_length=50)),
                ('cMembers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='cMembers', default=list, size=None)),
                ('cImage', models.CharField(db_column='cImage', default='', max_length=100)),
                ('cDesc', models.CharField(db_column='cDesc', default='', max_length=100)),
                ('cAdmin', models.IntegerField(db_column='cAdmin', default=0)),
                ('cCreated', models.DateTimeField(auto_now_add=True, db_column='cCreated')),
                ('cUpdated', models.DateTimeField(auto_now=True, db_column='cUpdated')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iSender', models.IntegerField(db_column='iSender', default=0)),
                ('iReceiver', models.IntegerField(db_column='iReceiver', default=0)),
                ('iCreated', models.DateTimeField(auto_now_add=True, db_column='iCreated')),
                ('iUpdated', models.DateTimeField(auto_now=True, db_column='iUpdated')),
                ('iRead', models.BooleanField(db_column='iRead', default=False)),
                ('iStatus', models.CharField(db_column='iStatus', default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mContent', models.TextField(db_column='mContent', default='')),
                ('mSender', models.IntegerField(db_column='mSender', default=0)),
                ('mReceiver', models.IntegerField(db_column='mReceiver', default=0)),
                ('mConversation', models.IntegerField(db_column='mConversation', default=0)),
                ('mCreated', models.DateTimeField(auto_now_add=True, db_column='mCreated')),
                ('mUpdated', models.DateTimeField(auto_now=True, db_column='mUpdated')),
                ('mRead', models.BooleanField(db_column='mRead', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uUsername', models.CharField(db_column='uUsername', default='', max_length=50, unique=True)),
                ('uEmail', models.CharField(db_column='uEmail', default='', max_length=64)),
                ('uFname', models.CharField(db_column='uFName', default='', max_length=64)),
                ('uLname', models.CharField(db_column='uLName', default='', max_length=64)),
                ('AFriends', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='AFriends', default=list, size=None)),
                ('ARequests', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='ARequests', default=list, size=None)),
                ('ABlocked', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='ABlocked', default=list, size=None)),
                ('ABlockedBy', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='ABlockedBy', default=list, size=None)),
                ('uprofilepic', models.ImageField(db_column='uProfilePic', default='/static/img/pfp/Default.png', upload_to='profile_pics/')),
                ('uprofilebgpic', models.ImageField(db_column='uProfileBgPic', default='', upload_to='profile_bg_pics/')),
                ('udesc', models.CharField(db_column='uDesc', default='', max_length=100)),
                ('isOnline', models.BooleanField(db_column='online', default=False)),
            ],
            options={
                'db_table': 'UserDataManagement_user',
                'managed': True,
            },
        ),
    ]
