version: '3.3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: SSarah
      POSTGRES_PASSWORD: ft_transgender
      POSTGRES_DB: RetroPong
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - RP_Network

networks:
  RP_Network:
    driver: host